### ISSUE TITLE
Add config option to allow extra flags to be passed to gjslint executable

### ISSUE THREAD

**Issue by WillsB3** [AtomLinter/linter-gjslint#17]
gjslint has a useful --strict flag that I'd like to be able to configure linter-gjslint to use.

We could either add support for each of the flags as separate options (nicer UI) but then that becomes a maintenance burden. So a simple text field that lets you specify extra flags that will be passed to the gjslint executable would probably be a good solution.

**Comment by artoale** [comment]
Agree, we should enable a set of flags to be passed as strings. @WillsB3 do you have time for a PR?

**Comment by trevershick** [comment]
I had time.  I just added it to the config file though, I didn't add a UI. that was going to be the next step.

**Comment by Arcanemagus** [comment]
BTW, as I'm sure you discovered: Atom will build the settings UI for you as long as the config section follows the spec.

**Comment by trevershick** [comment]
yeah. i realized that a little bit later as i was preparing to do ui work.

**Comment by artoale** [comment]
This has been closed by #19 and landed in v1.1.0! Thanks @trevershick !

**Comment by WillsB3** [comment]
Excellent! Thanks @trevershick
